#!/usr/bin/env sh

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
ITEM_DIR="$HOME/.config/sketchybar/items"
FONT_FACE="JetBrainsMono Nerd Font"

##### Bar Appearance #####
# https://felixkratz.github.io/SketchyBar/config/bar

sketchybar	--bar \
                height=32 \
                blur_radius=0 \
                position=top \
                sticky=on \
                padding_left=23 \
                padding_right=23 \
                display=main \
                color=0x00000000 \
                y_offset=10

sketchybar	--default \
                updates=when_shown \
                background.color=0xff24273a \
                background.padding_left=2 \
                background.padding_right=2 \
                background.corner_radius=5 \
                background.height=24 \
                icon.color=0xffffffff \
                icon.font="$FONT_FACE:Bold:17.0" \
                icon.padding_left=8 \
                icon.padding_right=7 \
                label.font="$FONT_FACE:Bold:14.0" \
                label.color=0xffcad3f5 \
                label.padding_left=0 \
                label.padding_right=7

# sketchybar	--add	item current_space left \
#             --set	current_space \
#                         background.color=0xfff5a97f \
#                         background.padding_right=5 \
#                         icon.font="$FONT_FACE:Bold:13.0" \
#                         icon.color=0xff24273a \
#                         label.drawing=off \
#                         script="$PLUGIN_DIR/current_space.sh" \
#             --subscribe current_space space_change mouse.clicked

# Left
source "$ITEM_DIR/spaces.sh"

# Center
source "$ITEM_DIR/front_app.sh"

# Right
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/battery.sh"


# SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"
# sketchybar	--add	item spotify_playlist e \
#             --set	spotify_playlist \
#                         background.padding_left=-5 \
#                         background.color=0xaa24273a \
#                         icon= \
#                         icon.color=0xffc6a0f6 \
#                         icon.font="$FONT_FACE:Bold:19.0" \
#                         label.drawing=off \
#                         script="$PLUGIN_DIR/spotify_playlist.sh" \
#             --subscribe spotify_playlist mouse.clicked

# sketchybar  --add   event spotify_change $SPOTIFY_EVENT \
#             --add   item spotify e \
#             --set   spotify \
#                         icon= \
#                     	icon.font="$FONT_FACE:Bold:20.0" \
#                     	icon.y_offset=1 \
#                         label.drawing=off \
#                     	label.padding_left=2 \
#                         script="$PLUGIN_DIR/spotify.sh" \
#             --subscribe spotify spotify_change mouse.clicked




##### Finalizing Setup #####
sketchybar --update
sketchybar --trigger space_change
